# Generated by Django 6.0 on 2025-12-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/avatar-placeholder.jpg', upload_to='avatars/'),
        ),
    ]
