# Generated by Django 6.0 on 2025-12-18 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_files_projectfiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
