# Generated by Django 6.0 on 2025-12-22 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_note_user'),
        ('projects', '0003_project_contributed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.projectstage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ManyToManyField(to='customers.customer'),
        ),
    ]
