# Generated by Django 6.0 on 2025-12-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectstage_remove_project_customer_project_stage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectFiles',
            new_name='ProjectFile',
        ),
    ]
