# Generated by Django 6.0 on 2025-12-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_customer_project_customers_projectnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='customers',
        ),
    ]
