# Generated by Django 6.0 on 2025-12-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_note_user'),
        ('projects', '0007_remove_project_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customers',
            field=models.ManyToManyField(to='customers.customer'),
        ),
    ]
