# Generated by Django 6.0 on 2025-12-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectstage',
            old_name='stage_name',
            new_name='name',
        ),
    ]
