# Generated by Django 6.0 on 2026-01-10 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectNote',
        ),
    ]
