# Generated by Django 6.0 on 2025-12-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_contact',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='next_contact',
            field=models.DateField(),
        ),
    ]
