# Generated by Django 6.0 on 2025-12-14 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customerfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.source'),
        ),
    ]
