# Generated by Django 6.0 on 2025-12-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
