# Generated by Django 6.0 on 2025-12-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_notes_remove_customer_comments_customer_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='notes',
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, to='customers.notes'),
        ),
    ]
