# Generated by Django 6.0 on 2026-01-09 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfiles',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='customers.customer'),
        ),
    ]
