# Generated by Django 6.0 on 2026-01-10 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_customerfiles_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
